package com.suitt.gk.assignment3.models;

public enum WeightDivisions {
    MINIMUM_WEIGHT, LIGHT_FLYWEIGHT,
    FLYWEIGHT, SUPER_FLYWEIGHT,
    BANTAMWEIGHT, SUPER_BANTAMWEIGHT,
    FEATHERWEIGHT, SUPER_FEATHERWEIGHT,
    LIGHTWEIGHT,
    SUPER_LIGHTWEIGHT,
    WELTERWEIGHT,
    SUPER_WELTERWEIGHT,
    MIDDLEWEIGHT,
    SUPER_MIDDLEWEIGHT,
    LIGHT_HEAVYWEIGHT,
    CRUISER_WEIGHT,
    HEAVYWEIGHT,
}
